Repository TeskaLabs/bspump, pull requests merged in 2018-10, with the labels that each got.

#44 Added FlattenDictProcessor to bspump
  bspump/common/__init__.py
  bspump/common/dict.py
Labels: enhancement

#49 Include bspump.web static folder in setup.py
  setup.py
Labels: bug

#48 alpine pyarrow build and installation doc
  doc/pyarrow/README.md
  doc/pyarrow/build.md
  doc/pyarrow/patch-0.11.0.diff
Labels: enhancement

#52 parquet sink rows rollover mechanism
  bspump-parquet.py
  bspump/parquet/sink.py
Labels: enhancement

#53 Add a duty-cycle metrics to Pipeline
  bspump/pipeline.py
Labels: enhancement

#51 Refactor of the lookup implementation.
  bspump-lookup.py
  bspump/abc/lookup.py
  bspump/service.py
Labels: refactoring

#56 Slack Sink
  bspump-slack.py
  bspump/slack/__init__.py
  bspump/slack/connection.py
  bspump/slack/sink.py
Labels: enhancement
